version: '3.9'

services:
  log-output:
    image: pingpong:v0.1
    container_name: pingpong
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    ports:
      - 5000:5000