apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      volumes:
        - name: files
      containers:
      - name: reader
        image: anastasiasafargalieva/app1
        volumeMounts:
          - name: files
            mountPath: /usr/src/app/files
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: writer
        image: anastasiasafargalieva/writer
        volumeMounts:
          - name: files
            mountPath: /usr/src/app/files
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"